export interface CatalogCategory {
  id: string;
  name: string;
  description: string;
}

export interface CatalogApplication {
  id: string;
  categoryId: string;
  name: string;
  description: string;
  officialUrl: string;
  tags: string[];
  resourceType: "application" | "website";
  websiteTarget?: string;
  executableNames?: string[];
  pathFragments?: string[];
  privacyNotice?: string;
}

const AI_SERVICE_NOTICE =
  "입력한 대화, 코드 또는 파일이 외부 AI 서비스로 전송될 수 있습니다. 기밀 정보 입력 전 해당 서비스의 개인정보 처리 정책을 확인하세요.";

export const catalogCategories: CatalogCategory[] = [
  { id: "development", name: "개발", description: "코딩, 버전 관리와 API 개발" },
  {
    id: "ai-coding",
    name: "AI 개발 도구",
    description: "AI 코딩 에이전트, 편집기와 IDE 확장",
  },
  { id: "reversing", name: "리버싱", description: "바이너리 분석과 디버깅" },
  { id: "forensics", name: "디지털 포렌식", description: "디스크, 메모리와 네트워크 분석" },
  { id: "security", name: "보안", description: "웹, 네트워크와 암호 분석" },
  { id: "ai", name: "AI", description: "로컬 LLM과 이미지 생성" },
  { id: "browsers", name: "브라우저", description: "웹 브라우저와 개인정보 보호 탐색" },
  { id: "office", name: "문서·업무", description: "오피스, PDF와 이메일 업무" },
  { id: "communication", name: "소통", description: "메신저, 회의와 팀 협업" },
  { id: "storage", name: "파일·클라우드", description: "파일 전송, 동기화와 탐색" },
  { id: "utilities", name: "유틸리티", description: "압축, 시스템 관리와 미디어 재생" },
  { id: "media", name: "영상·디자인", description: "영상 편집, 녹화와 그래픽 작업" },
  { id: "notes", name: "메모·생산성", description: "지식 관리, 문서와 연구 자료" },
  { id: "data", name: "데이터", description: "분석, 시각화와 데이터 과학" },
];

export const catalogApplications: CatalogApplication[] = [
  app(
    "chatgpt-desktop",
    "ai",
    "ChatGPT",
    "대화, 코드 작성과 분석을 지원하는 OpenAI 데스크톱 앱",
    "https://chatgpt.com/download/",
    ["AI", "코딩", "데스크톱"],
    ["chatgpt.exe"],
  ),
  app(
    "claude-desktop",
    "ai",
    "Claude",
    "대화, 문서 분석과 글쓰기를 지원하는 Anthropic 데스크톱 앱",
    "https://claude.com/download",
    ["AI", "Claude Code", "코딩"],
    ["claude.exe"],
  ),
  app(
    "codex-desktop",
    "ai-coding",
    "Codex",
    "프로젝트를 읽고 코드 작업을 수행하는 OpenAI 개발 에이전트",
    "https://chatgpt.com/codex",
    ["AI", "에이전트", "코딩"],
    ["codex.exe"],
  ),
  app(
    "github-copilot-app",
    "ai-coding",
    "GitHub Copilot",
    "저장소와 코딩 작업을 지원하는 GitHub의 AI 개발 도구",
    "https://github.com/features/copilot",
    ["AI", "GitHub", "코딩"],
    ["github copilot.exe", "copilot.exe"],
  ),
  app(
    "cursor",
    "ai-coding",
    "Cursor",
    "코드베이스 문맥을 활용하는 AI 코드 편집기",
    "https://cursor.com/en-US/download",
    ["AI", "편집기", "에이전트"],
    ["cursor.exe"],
  ),
  app(
    "windsurf",
    "ai-coding",
    "Windsurf",
    "에이전트 기반 개발 흐름을 제공하는 AI 코드 편집기",
    "https://windsurf.com/editor",
    ["AI", "편집기", "에이전트"],
    ["windsurf.exe"],
  ),
  app(
    "perplexity-desktop",
    "ai",
    "Perplexity",
    "웹 검색과 출처 기반 답변을 제공하는 AI 데스크톱 앱",
    "https://www.perplexity.ai/platforms",
    ["AI", "검색", "리서치"],
    ["perplexity.exe"],
  ),
  app(
    "vscode",
    "development",
    "Visual Studio Code",
    "확장성이 높은 코드 편집기",
    "https://code.visualstudio.com/",
    ["개발", "편집기"],
    ["code.exe"],
  ),
  app(
    "visual-studio",
    "development",
    "Visual Studio Community",
    "Windows 및 .NET 통합 개발 환경",
    "https://visualstudio.microsoft.com/vs/community/",
    ["개발", "IDE", ".NET"],
    ["devenv.exe"],
  ),
  app(
    "git",
    "development",
    "Git",
    "분산 버전 관리 도구",
    "https://git-scm.com/download/win",
    ["개발", "버전 관리"],
    ["git.exe", "git-gui.exe"],
  ),
  app(
    "docker",
    "development",
    "Docker Desktop",
    "컨테이너 개발 및 실행 환경",
    "https://www.docker.com/products/docker-desktop/",
    ["개발", "컨테이너"],
    ["docker desktop.exe"],
  ),
  app(
    "postman",
    "development",
    "Postman",
    "API 설계와 테스트 도구",
    "https://www.postman.com/downloads/",
    ["개발", "API"],
    ["postman.exe"],
  ),
  app(
    "chrome",
    "browsers",
    "Google Chrome",
    "Google 계정 동기화와 확장 기능을 지원하는 웹 브라우저",
    "https://www.google.com/chrome/",
    ["브라우저", "웹", "Google"],
    ["chrome.exe"],
  ),
  app(
    "edge",
    "browsers",
    "Microsoft Edge",
    "Windows와 Microsoft 서비스에 통합된 웹 브라우저",
    "https://www.microsoft.com/edge/download",
    ["브라우저", "웹", "Microsoft"],
    ["msedge.exe"],
  ),
  app(
    "firefox",
    "browsers",
    "Mozilla Firefox",
    "Mozilla가 개발하는 오픈소스 웹 브라우저",
    "https://www.firefox.com/download/windows/",
    ["브라우저", "웹", "오픈소스"],
    ["firefox.exe"],
    ["\\mozilla firefox\\"],
  ),
  app(
    "brave",
    "browsers",
    "Brave",
    "추적 방지 기능을 기본 제공하는 웹 브라우저",
    "https://brave.com/download/",
    ["브라우저", "개인정보 보호", "웹"],
    ["brave.exe"],
  ),
  app(
    "vivaldi",
    "browsers",
    "Vivaldi",
    "탭과 인터페이스를 세밀하게 구성할 수 있는 웹 브라우저",
    "https://vivaldi.com/download/?platform=windows",
    ["브라우저", "사용자 지정", "웹"],
    ["vivaldi.exe"],
  ),
  app(
    "opera",
    "browsers",
    "Opera",
    "사이드바와 작업 공간 기능을 제공하는 웹 브라우저",
    "https://www.opera.com/download",
    ["브라우저", "웹", "작업 공간"],
    ["opera.exe"],
    ["\\opera\\"],
  ),
  app(
    "tor-browser",
    "browsers",
    "Tor Browser",
    "Tor 네트워크를 사용하는 개인정보 보호 중심 브라우저",
    "https://www.torproject.org/download/",
    ["브라우저", "개인정보 보호", "Tor"],
    [],
    ["\\tor browser\\"],
  ),
  app(
    "microsoft-word",
    "office",
    "Microsoft Word",
    "문서 작성과 검토를 위한 워드 프로세서",
    "https://www.microsoft.com/microsoft-365/word",
    ["문서", "Office", "업무"],
    ["winword.exe"],
  ),
  app(
    "microsoft-excel",
    "office",
    "Microsoft Excel",
    "스프레드시트 작성과 데이터 분석 도구",
    "https://www.microsoft.com/microsoft-365/excel",
    ["스프레드시트", "Office", "데이터"],
    ["excel.exe"],
  ),
  app(
    "microsoft-powerpoint",
    "office",
    "Microsoft PowerPoint",
    "프레젠테이션 제작과 발표 도구",
    "https://www.microsoft.com/microsoft-365/powerpoint",
    ["프레젠테이션", "Office", "업무"],
    ["powerpnt.exe"],
  ),
  app(
    "libreoffice",
    "office",
    "LibreOffice",
    "문서, 스프레드시트와 프레젠테이션을 지원하는 오픈소스 오피스",
    "https://www.libreoffice.org/download/download-libreoffice/",
    ["문서", "오픈소스", "Office"],
    ["soffice.exe", "swriter.exe", "scalc.exe", "simpress.exe"],
  ),
  app(
    "adobe-acrobat-reader",
    "office",
    "Adobe Acrobat Reader",
    "PDF 열람, 주석과 서명을 지원하는 문서 도구",
    "https://get.adobe.com/reader/",
    ["PDF", "문서", "서명"],
    ["acrord32.exe", "acrobat.exe"],
  ),
  app(
    "sumatra-pdf",
    "office",
    "SumatraPDF",
    "가볍고 빠른 오픈소스 PDF·전자책 뷰어",
    "https://www.sumatrapdfreader.org/download-free-pdf-viewer",
    ["PDF", "전자책", "오픈소스"],
    ["sumatrapdf.exe"],
  ),
  app(
    "thunderbird",
    "office",
    "Mozilla Thunderbird",
    "이메일, 일정과 주소록을 관리하는 오픈소스 클라이언트",
    "https://www.thunderbird.net/download/",
    ["이메일", "일정", "오픈소스"],
    ["thunderbird.exe"],
  ),
  app(
    "slack",
    "communication",
    "Slack",
    "채널 기반 팀 메시징과 협업 도구",
    "https://slack.com/downloads/windows",
    ["메신저", "협업", "업무"],
    ["slack.exe"],
  ),
  app(
    "discord",
    "communication",
    "Discord",
    "커뮤니티용 문자, 음성 및 영상 대화 앱",
    "https://discord.com/download",
    ["메신저", "음성", "커뮤니티"],
    ["discord.exe"],
  ),
  app(
    "microsoft-teams",
    "communication",
    "Microsoft Teams",
    "회의, 채팅과 Microsoft 365 협업 도구",
    "https://www.microsoft.com/microsoft-teams/download-app",
    ["회의", "협업", "Microsoft"],
    ["ms-teams.exe", "teams.exe"],
  ),
  app(
    "zoom",
    "communication",
    "Zoom Workplace",
    "영상 회의와 화면 공유를 지원하는 협업 앱",
    "https://zoom.us/download",
    ["회의", "영상", "화면 공유"],
    ["zoom.exe"],
  ),
  app(
    "telegram",
    "communication",
    "Telegram Desktop",
    "다중 기기 동기화를 지원하는 메시징 앱",
    "https://desktop.telegram.org/",
    ["메신저", "커뮤니티", "동기화"],
    ["telegram.exe"],
  ),
  app(
    "signal",
    "communication",
    "Signal Desktop",
    "종단간 암호화를 사용하는 메시징 앱",
    "https://signal.org/download/",
    ["메신저", "암호화", "개인정보 보호"],
    ["signal.exe"],
  ),
  app(
    "onedrive",
    "storage",
    "Microsoft OneDrive",
    "Windows와 Microsoft 365에 연결되는 클라우드 동기화 앱",
    "https://www.microsoft.com/microsoft-365/onedrive/download",
    ["클라우드", "동기화", "Microsoft"],
    ["onedrive.exe"],
  ),
  app(
    "google-drive",
    "storage",
    "Google Drive for desktop",
    "Google Drive 파일 스트리밍과 동기화 앱",
    "https://www.google.com/drive/download/",
    ["클라우드", "동기화", "Google"],
    ["googledrivefs.exe"],
  ),
  app(
    "dropbox",
    "storage",
    "Dropbox",
    "파일 백업, 공유와 클라우드 동기화 앱",
    "https://www.dropbox.com/install",
    ["클라우드", "동기화", "백업"],
    ["dropbox.exe"],
  ),
  app(
    "winscp",
    "storage",
    "WinSCP",
    "SFTP, FTP와 SCP를 지원하는 Windows 파일 전송 도구",
    "https://winscp.net/eng/download.php",
    ["SFTP", "FTP", "파일 전송"],
    ["winscp.exe"],
  ),
  app(
    "filezilla",
    "storage",
    "FileZilla Client",
    "FTP와 SFTP 파일 전송을 지원하는 오픈소스 클라이언트",
    "https://filezilla-project.org/download.php?type=client",
    ["FTP", "SFTP", "오픈소스"],
    ["filezilla.exe"],
  ),
  app(
    "total-commander",
    "storage",
    "Total Commander",
    "이중 창 기반 Windows 파일 관리자",
    "https://www.ghisler.com/download.htm",
    ["파일 관리", "탐색", "생산성"],
    ["totalcmd64.exe", "totalcmd.exe"],
  ),
  app(
    "everything-search",
    "storage",
    "Everything",
    "Windows 파일 이름을 빠르게 검색하는 도구",
    "https://www.voidtools.com/downloads/",
    ["파일 검색", "Windows", "생산성"],
    ["everything.exe", "everything64.exe"],
  ),
  app(
    "seven-zip",
    "utilities",
    "7-Zip",
    "다양한 압축 형식을 지원하는 오픈소스 압축 도구",
    "https://www.7-zip.org/download.html",
    ["압축", "파일", "오픈소스"],
    ["7zfm.exe", "7zg.exe"],
  ),
  app(
    "winrar",
    "utilities",
    "WinRAR",
    "RAR와 ZIP을 지원하는 압축 파일 관리 도구",
    "https://www.win-rar.com/download.html",
    ["압축", "파일", "RAR"],
    ["winrar.exe"],
  ),
  app(
    "powertoys",
    "utilities",
    "Microsoft PowerToys",
    "창 배치, 키 매핑과 빠른 실행 등 Windows 생산성 도구 모음",
    "https://learn.microsoft.com/windows/powertoys/install",
    ["Windows", "생산성", "시스템"],
    ["powertoys.exe", "powertoys.settings.exe"],
  ),
  app(
    "sharex",
    "utilities",
    "ShareX",
    "화면 캡처, 녹화와 작업 자동화를 지원하는 오픈소스 도구",
    "https://getsharex.com/downloads",
    ["화면 캡처", "녹화", "오픈소스"],
    ["sharex.exe"],
  ),
  app(
    "vlc",
    "utilities",
    "VLC media player",
    "다양한 오디오와 영상 형식을 재생하는 오픈소스 플레이어",
    "https://www.videolan.org/vlc/download-windows.html",
    ["미디어", "영상", "오픈소스"],
    ["vlc.exe"],
  ),
  app(
    "notepad-plus-plus",
    "utilities",
    "Notepad++",
    "다양한 형식과 플러그인을 지원하는 Windows 텍스트 편집기",
    "https://notepad-plus-plus.org/downloads/",
    ["텍스트", "편집기", "오픈소스"],
    ["notepad++.exe"],
  ),
  app(
    "rufus",
    "utilities",
    "Rufus",
    "부팅 가능한 USB 드라이브를 만드는 도구",
    "https://rufus.ie/",
    ["USB", "부팅", "시스템"],
    ["rufus.exe", "rufus_x64.exe"],
    ["\\rufus"],
  ),
  app(
    "crystaldiskinfo",
    "utilities",
    "CrystalDiskInfo",
    "HDD와 SSD의 상태 및 S.M.A.R.T. 정보를 확인하는 도구",
    "https://crystalmark.info/en/software/crystaldiskinfo/",
    ["디스크", "상태 확인", "시스템"],
    ["diskinfo64.exe", "diskinfo32.exe"],
  ),
  app(
    "hwinfo",
    "utilities",
    "HWiNFO",
    "PC 하드웨어 정보와 센서를 확인하는 시스템 진단 도구",
    "https://www.hwinfo.com/download/",
    ["하드웨어", "센서", "진단"],
    ["hwinfo64.exe", "hwinfo32.exe"],
  ),
  app(
    "ghidra",
    "reversing",
    "Ghidra",
    "소프트웨어 리버싱 프레임워크",
    "https://github.com/NationalSecurityAgency/ghidra/releases",
    ["리버싱", "디스어셈블러"],
    ["ghidra.exe"],
    ["\\ghidra_"],
  ),
  app(
    "x64dbg",
    "reversing",
    "x64dbg",
    "Windows 32·64비트 사용자 모드 디버거",
    "https://x64dbg.com/",
    ["리버싱", "디버거"],
    ["x64dbg.exe", "x32dbg.exe"],
  ),
  app(
    "ida-free",
    "reversing",
    "IDA Free",
    "무료 바이너리 분석 도구",
    "https://hex-rays.com/ida-free",
    ["리버싱", "디스어셈블러"],
    ["ida.exe", "ida64.exe"],
  ),
  app(
    "die",
    "reversing",
    "Detect It Easy",
    "파일 형식과 패커 탐지 도구",
    "https://github.com/horsicq/DIE-engine/releases",
    ["리버싱", "파일 분석"],
    ["die.exe", "diec.exe"],
  ),
  app(
    "pe-bear",
    "reversing",
    "PE-bear",
    "Windows PE 파일 분석 도구",
    "https://github.com/hasherezade/pe-bear-releases",
    ["리버싱", "PE"],
    ["pe-bear.exe"],
  ),
  app(
    "autopsy",
    "forensics",
    "Autopsy",
    "디스크 이미지와 파일 시스템 포렌식 플랫폼",
    "https://www.autopsy.com/download/",
    ["포렌식", "디스크"],
    ["autopsy.exe", "autopsy64.exe"],
  ),
  app(
    "wireshark",
    "forensics",
    "Wireshark",
    "패킷 캡처와 네트워크 프로토콜 분석",
    "https://www.wireshark.org/download.html",
    ["포렌식", "네트워크"],
    ["wireshark.exe"],
  ),
  app(
    "volatility",
    "forensics",
    "Volatility 3",
    "메모리 포렌식 프레임워크",
    "https://github.com/volatilityfoundation/volatility3",
    ["포렌식", "메모리"],
    ["vol.exe", "volatility.exe"],
    ["\\volatility3\\"],
  ),
  app(
    "ftk-imager",
    "forensics",
    "FTK Imager",
    "포렌식 이미지 생성과 증거 미리보기",
    "https://www.exterro.com/digital-forensics-software/ftk-imager",
    ["포렌식", "이미징"],
    ["ftk imager.exe", "ftkimager.exe"],
  ),
  app(
    "sqlite-browser",
    "forensics",
    "DB Browser for SQLite",
    "SQLite 데이터베이스 탐색과 분석",
    "https://sqlitebrowser.org/dl/",
    ["포렌식", "데이터베이스"],
    ["db browser for sqlite.exe", "sqlitebrowser.exe"],
  ),
  app(
    "burp",
    "security",
    "Burp Suite Community",
    "웹 애플리케이션 보안 테스트 도구",
    "https://portswigger.net/burp/communitydownload",
    ["보안", "웹"],
    ["burpsuitecommunity.exe", "burp suite community edition.exe"],
  ),
  app(
    "nmap",
    "security",
    "Nmap",
    "네트워크 탐색과 포트 스캐닝",
    "https://nmap.org/download.html",
    ["보안", "네트워크"],
    ["zenmap.exe", "nmap.exe"],
  ),
  app(
    "zap",
    "security",
    "OWASP ZAP",
    "오픈소스 웹 애플리케이션 보안 스캐너",
    "https://www.zaproxy.org/download/",
    ["보안", "웹", "OWASP"],
    ["zap.exe", "zaproxy.exe"],
  ),
  app(
    "hashcat",
    "security",
    "Hashcat",
    "패스워드 복구와 해시 분석",
    "https://hashcat.net/hashcat/",
    ["보안", "암호"],
    ["hashcat.exe"],
  ),
  website(
    "cyberchef",
    "security",
    "CyberChef",
    "브라우저 데이터 변환·분석 도구",
    "https://gchq.github.io/CyberChef/",
    ["보안", "인코딩", "웹 도구"],
  ),
  app(
    "ollama",
    "ai",
    "Ollama",
    "로컬에서 LLM을 실행하고 관리하는 도구",
    "https://ollama.com/download/windows",
    ["AI", "로컬 LLM"],
    ["ollama app.exe", "ollama.exe"],
  ),
  app(
    "lm-studio",
    "ai",
    "LM Studio",
    "로컬 언어 모델 탐색과 실행",
    "https://lmstudio.ai/download",
    ["AI", "로컬 LLM"],
    ["lm studio.exe"],
  ),
  app(
    "comfyui",
    "ai",
    "ComfyUI",
    "노드 기반 이미지·영상 생성 워크플로",
    "https://www.comfy.org/download",
    ["AI", "이미지 생성"],
    ["comfyui.exe", "comfyui desktop.exe"],
  ),
  app(
    "anythingllm",
    "ai",
    "AnythingLLM",
    "로컬 문서 기반 AI와 RAG 작업 공간",
    "https://anythingllm.com/desktop",
    ["AI", "RAG"],
    ["anythingllm.exe"],
  ),
  app(
    "jan",
    "ai",
    "Jan",
    "오픈소스 로컬 AI 데스크톱 앱",
    "https://jan.ai/",
    ["AI", "로컬 LLM"],
    ["jan.exe"],
  ),
  app(
    "davinci",
    "media",
    "DaVinci Resolve",
    "영상 편집, 색보정과 후반 작업",
    "https://www.blackmagicdesign.com/products/davinciresolve",
    ["영상", "편집"],
    ["resolve.exe"],
  ),
  app(
    "blender",
    "media",
    "Blender",
    "3D 제작, 합성과 영상 편집",
    "https://www.blender.org/download/",
    ["3D", "영상", "디자인"],
    ["blender.exe"],
  ),
  app(
    "obs",
    "media",
    "OBS Studio",
    "화면 녹화와 라이브 스트리밍",
    "https://obsproject.com/download",
    ["영상", "녹화", "스트리밍"],
    ["obs64.exe", "obs32.exe"],
  ),
  app(
    "handbrake",
    "media",
    "HandBrake",
    "오픈소스 영상 변환과 인코딩",
    "https://handbrake.fr/downloads.php",
    ["영상", "인코딩"],
    ["handbrake.exe"],
  ),
  app(
    "shotcut",
    "media",
    "Shotcut",
    "오픈소스 영상 편집기",
    "https://shotcut.org/download/",
    ["영상", "편집"],
    ["shotcut.exe"],
  ),
  app(
    "obsidian",
    "notes",
    "Obsidian",
    "로컬 Markdown 기반 지식 관리",
    "https://obsidian.md/download",
    ["메모", "지식 관리"],
    ["obsidian.exe"],
  ),
  app(
    "joplin",
    "notes",
    "Joplin",
    "오픈소스 메모와 할 일 관리",
    "https://joplinapp.org/help/install/",
    ["메모", "오픈소스"],
    ["joplin.exe"],
  ),
  app(
    "logseq",
    "notes",
    "Logseq",
    "아웃라이너 기반 로컬 지식 관리",
    "https://logseq.com/downloads",
    ["메모", "지식 관리"],
    ["logseq.exe"],
  ),
  app(
    "notion",
    "notes",
    "Notion",
    "문서, 데이터베이스와 협업 작업 공간",
    "https://www.notion.com/desktop",
    ["메모", "협업"],
    ["notion.exe"],
  ),
  app(
    "zotero",
    "notes",
    "Zotero",
    "연구 자료와 인용 문헌 관리",
    "https://www.zotero.org/download/",
    ["연구", "문헌 관리"],
    ["zotero.exe"],
  ),
  app(
    "python",
    "data",
    "Python",
    "데이터 분석과 자동화용 프로그래밍 언어",
    "https://www.python.org/downloads/windows/",
    ["데이터", "개발"],
    ["python.exe", "pythonw.exe"],
  ),
  app(
    "rstudio",
    "data",
    "RStudio Desktop",
    "R 데이터 분석 통합 개발 환경",
    "https://posit.co/download/rstudio-desktop/",
    ["데이터", "통계"],
    ["rstudio.exe"],
  ),
  app(
    "power-bi",
    "data",
    "Power BI Desktop",
    "대화형 데이터 분석과 시각화",
    "https://www.microsoft.com/en-us/power-platform/products/power-bi/desktop",
    ["데이터", "BI", "시각화"],
    ["pbidesktop.exe"],
  ),
  app(
    "orange",
    "data",
    "Orange Data Mining",
    "시각적 데이터 분석과 머신러닝",
    "https://orangedatamining.com/download/",
    ["데이터", "머신러닝"],
    ["orange-canvas.exe", "orange.exe"],
  ),
  app(
    "tableau-public",
    "data",
    "Tableau Public",
    "공개 데이터 시각화 제작 도구",
    "https://www.tableau.com/products/public/download",
    ["데이터", "시각화"],
    ["tableau.exe", "tableau public.exe"],
  ),
  website(
    "mdn",
    "development",
    "MDN Web Docs",
    "웹 표준과 브라우저 API 문서",
    "https://developer.mozilla.org/",
    ["개발", "문서", "웹"],
  ),
  website(
    "github-web",
    "development",
    "GitHub",
    "소스 코드 저장소와 협업 플랫폼",
    "https://github.com/",
    ["개발", "Git", "협업"],
  ),
  website(
    "stackoverflow",
    "development",
    "Stack Overflow",
    "개발자 질문과 답변 검색",
    "https://stackoverflow.com/",
    ["개발", "Q&A"],
  ),
  website(
    "devdocs",
    "development",
    "DevDocs",
    "여러 개발 문서를 한곳에서 검색",
    "https://devdocs.io/",
    ["개발", "문서", "검색"],
  ),

  website(
    "ost2",
    "reversing",
    "OpenSecurityTraining2",
    "리버싱과 시스템 보안 무료 학습 과정",
    "https://opensecuritytraining.info/",
    ["리버싱", "학습", "보안"],
  ),
  website(
    "compiler-explorer",
    "reversing",
    "Compiler Explorer",
    "컴파일 결과와 어셈블리 코드를 비교",
    "https://godbolt.org/",
    ["리버싱", "어셈블리", "컴파일러"],
  ),
  website(
    "dogbolt",
    "reversing",
    "Dogbolt",
    "여러 디컴파일러의 결과를 비교",
    "https://dogbolt.org/",
    ["리버싱", "디컴파일러", "웹 도구"],
    "분석 파일이 외부 서비스로 전송될 수 있습니다. 민감한 파일은 업로드하지 마세요.",
  ),
  website(
    "pe-format",
    "reversing",
    "Microsoft PE Format",
    "Windows PE·COFF 파일 형식 공식 문서",
    "https://learn.microsoft.com/en-us/windows/win32/debug/pe-format",
    ["리버싱", "PE", "문서"],
  ),

  website(
    "cyberdefenders",
    "forensics",
    "CyberDefenders",
    "디지털 포렌식과 블루팀 실습",
    "https://cyberdefenders.org/",
    ["포렌식", "실습", "블루팀"],
  ),
  website(
    "mitre-attack",
    "forensics",
    "MITRE ATT&CK",
    "공격 전술과 기술 지식 베이스",
    "https://attack.mitre.org/",
    ["포렌식", "위협 분석", "지식 베이스"],
  ),
  website(
    "virustotal",
    "forensics",
    "VirusTotal",
    "파일, URL과 해시 평판 분석",
    "https://www.virustotal.com/gui/home/upload",
    ["포렌식", "악성코드", "평판"],
    "업로드한 파일이나 URL 정보가 외부 서비스에 공유될 수 있습니다. 기밀 자료는 업로드하지 마세요.",
  ),
  website(
    "hybrid-analysis",
    "forensics",
    "Hybrid Analysis",
    "악성코드 동적 분석 샌드박스",
    "https://www.hybrid-analysis.com/",
    ["포렌식", "악성코드", "샌드박스"],
    "분석 파일이 외부 샌드박스로 전송됩니다. 개인정보나 기밀 자료를 업로드하지 마세요.",
  ),

  website(
    "owasp-cheatsheets",
    "security",
    "OWASP Cheat Sheet Series",
    "애플리케이션 보안 실무 지침",
    "https://cheatsheetseries.owasp.org/",
    ["보안", "웹", "가이드"],
  ),
  website(
    "shodan",
    "security",
    "Shodan",
    "인터넷 연결 장비와 서비스 검색",
    "https://www.shodan.io/",
    ["보안", "OSINT", "네트워크"],
  ),
  website(
    "urlscan",
    "security",
    "urlscan.io",
    "웹사이트 요청과 동작 분석",
    "https://urlscan.io/",
    ["보안", "URL", "분석"],
    "제출한 URL과 분석 결과가 공개될 수 있습니다. 내부 주소나 비공개 링크를 제출하지 마세요.",
  ),
  website(
    "hibp",
    "security",
    "Have I Been Pwned",
    "계정과 이메일 유출 여부 확인",
    "https://haveibeenpwned.com/",
    ["보안", "계정", "유출 확인"],
  ),

  website(
    "claude-code-docs",
    "ai-coding",
    "Claude Code",
    "터미널에서 프로젝트를 다루는 Anthropic의 코딩 에이전트",
    "https://code.claude.com/docs/en/overview",
    ["AI", "CLI", "에이전트"],
    AI_SERVICE_NOTICE,
  ),
  website(
    "codex-cli",
    "ai-coding",
    "Codex CLI",
    "터미널에서 로컬 코드 작업을 수행하는 OpenAI 코딩 에이전트",
    "https://github.com/openai/codex",
    ["AI", "CLI", "에이전트"],
    AI_SERVICE_NOTICE,
  ),
  website(
    "github-copilot",
    "ai-coding",
    "GitHub Copilot for IDE",
    "VS Code와 JetBrains 등에서 사용하는 AI 코딩 도우미",
    "https://github.com/features/copilot",
    ["AI", "IDE 확장", "GitHub"],
    AI_SERVICE_NOTICE,
  ),
  website(
    "amazon-q-developer",
    "ai-coding",
    "Amazon Q Developer",
    "IDE와 명령줄에서 코드 작성과 AWS 개발을 돕는 AI 도구",
    "https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/what-is.html",
    ["AI", "IDE 확장", "AWS"],
    AI_SERVICE_NOTICE,
  ),
  website(
    "gemini-cli",
    "ai-coding",
    "Gemini CLI",
    "터미널에서 Gemini를 사용하는 오픈소스 AI 에이전트",
    "https://github.com/google-gemini/gemini-cli",
    ["AI", "CLI", "에이전트"],
    AI_SERVICE_NOTICE,
  ),
  website(
    "cline",
    "ai-coding",
    "Cline",
    "사용자 승인 기반으로 코드를 수정하고 명령을 실행하는 IDE 에이전트",
    "https://cline.bot/",
    ["AI", "IDE 확장", "에이전트"],
    AI_SERVICE_NOTICE,
  ),
  website(
    "aider",
    "ai-coding",
    "Aider",
    "Git 저장소와 함께 사용하는 터미널 AI 페어 프로그래밍 도구",
    "https://aider.chat/",
    ["AI", "CLI", "Git"],
    AI_SERVICE_NOTICE,
  ),
  website(
    "chatgpt-web",
    "ai",
    "ChatGPT Web",
    "브라우저에서 사용하는 OpenAI의 AI 도우미",
    "https://chatgpt.com/",
    ["AI", "대화", "웹"],
    AI_SERVICE_NOTICE,
  ),
  website(
    "claude-web",
    "ai",
    "Claude Web",
    "브라우저에서 사용하는 Anthropic의 AI 도우미",
    "https://claude.ai/",
    ["AI", "대화", "웹"],
    AI_SERVICE_NOTICE,
  ),
  website(
    "microsoft-copilot",
    "ai",
    "Microsoft Copilot",
    "Microsoft의 웹 기반 AI 도우미",
    "https://copilot.microsoft.com/",
    ["AI", "대화", "Microsoft"],
    AI_SERVICE_NOTICE,
  ),
  website(
    "gemini-web",
    "ai",
    "Google Gemini",
    "Google의 멀티모달 AI 도우미",
    "https://gemini.google.com/",
    ["AI", "대화", "Google"],
    AI_SERVICE_NOTICE,
  ),
  website(
    "perplexity-web",
    "ai",
    "Perplexity Web",
    "웹 검색과 출처를 결합한 AI 리서치 서비스",
    "https://www.perplexity.ai/",
    ["AI", "검색", "리서치"],
    AI_SERVICE_NOTICE,
  ),
  website(
    "notebooklm",
    "ai",
    "NotebookLM",
    "업로드한 자료를 바탕으로 정리하고 질문하는 AI 연구 도우미",
    "https://notebooklm.google.com/",
    ["AI", "문서", "리서치"],
    AI_SERVICE_NOTICE,
  ),
  website(
    "google-ai-studio",
    "ai",
    "Google AI Studio",
    "Gemini 모델 프롬프트와 API를 시험하는 개발 환경",
    "https://aistudio.google.com/",
    ["AI", "API", "프롬프트"],
    AI_SERVICE_NOTICE,
  ),
  website(
    "mistral-le-chat",
    "ai",
    "Le Chat",
    "Mistral AI의 웹 기반 AI 도우미",
    "https://chat.mistral.ai/chat",
    ["AI", "대화", "웹"],
    AI_SERVICE_NOTICE,
  ),
  website(
    "deepseek-chat",
    "ai",
    "DeepSeek Chat",
    "DeepSeek의 웹 기반 AI 대화 서비스",
    "https://chat.deepseek.com/",
    ["AI", "대화", "웹"],
    AI_SERVICE_NOTICE,
  ),
  website(
    "grok",
    "ai",
    "Grok",
    "xAI의 웹 기반 AI 도우미",
    "https://grok.com/",
    ["AI", "대화", "웹"],
    AI_SERVICE_NOTICE,
  ),
  website(
    "poe",
    "ai",
    "Poe",
    "여러 AI 모델과 사용자 제작 봇을 이용하는 서비스",
    "https://poe.com/",
    ["AI", "대화", "멀티 모델"],
    AI_SERVICE_NOTICE,
  ),
  website(
    "huggingface",
    "ai",
    "Hugging Face",
    "AI 모델과 데이터셋 탐색",
    "https://huggingface.co/",
    ["AI", "모델", "데이터셋"],
  ),
  website(
    "ollama-library",
    "ai",
    "Ollama Model Library",
    "Ollama에서 실행할 로컬 모델 탐색",
    "https://ollama.com/library",
    ["AI", "로컬 LLM", "모델"],
  ),
  website(
    "papers-with-code",
    "ai",
    "Papers with Code",
    "AI 논문과 공개 구현 탐색",
    "https://paperswithcode.com/",
    ["AI", "논문", "코드"],
  ),
  website(
    "openai-docs",
    "ai",
    "OpenAI API Docs",
    "OpenAI API 공식 개발 문서",
    "https://platform.openai.com/docs/",
    ["AI", "API", "문서"],
  ),

  website(
    "photopea",
    "media",
    "Photopea",
    "브라우저 기반 이미지 편집 도구",
    "https://www.photopea.com/",
    ["디자인", "이미지", "웹 도구"],
  ),
  website("canva", "media", "Canva", "템플릿 기반 디자인과 영상 제작", "https://www.canva.com/", [
    "디자인",
    "영상",
    "템플릿",
  ]),
  website(
    "adobe-express",
    "media",
    "Adobe Express",
    "브라우저 기반 콘텐츠 제작",
    "https://www.adobe.com/express/",
    ["디자인", "영상", "웹 도구"],
  ),
  website("pexels", "media", "Pexels", "사진과 영상 소스 탐색", "https://www.pexels.com/", [
    "영상",
    "사진",
    "소스",
  ]),

  website(
    "excalidraw",
    "notes",
    "Excalidraw",
    "손그림 스타일 다이어그램과 화이트보드",
    "https://excalidraw.com/",
    ["메모", "다이어그램", "화이트보드"],
  ),
  website(
    "google-keep",
    "notes",
    "Google Keep",
    "간단한 메모와 체크리스트",
    "https://keep.google.com/",
    ["메모", "체크리스트"],
  ),
  website("todoist", "notes", "Todoist", "할 일과 프로젝트 관리", "https://todoist.com/app", [
    "생산성",
    "할 일",
  ]),
  website("miro", "notes", "Miro", "협업용 온라인 화이트보드", "https://miro.com/app/", [
    "생산성",
    "협업",
    "화이트보드",
  ]),

  website(
    "kaggle",
    "data",
    "Kaggle",
    "데이터셋, 노트북과 데이터 경진대회",
    "https://www.kaggle.com/",
    ["데이터", "머신러닝", "데이터셋"],
  ),
  website(
    "colab",
    "data",
    "Google Colab",
    "브라우저에서 실행하는 Python 노트북",
    "https://colab.research.google.com/",
    ["데이터", "Python", "노트북"],
  ),
  website(
    "observable",
    "data",
    "Observable",
    "데이터 분석과 대화형 시각화",
    "https://observablehq.com/",
    ["데이터", "시각화", "노트북"],
  ),
  website(
    "our-world-in-data",
    "data",
    "Our World in Data",
    "공개 통계 데이터와 시각화",
    "https://ourworldindata.org/",
    ["데이터", "통계", "공개 자료"],
  ),
];

function app(
  id: string,
  categoryId: string,
  name: string,
  description: string,
  officialUrl: string,
  tags: string[],
  executableNames: string[],
  pathFragments?: string[],
): CatalogApplication {
  return {
    id,
    categoryId,
    name,
    description,
    officialUrl,
    tags,
    resourceType: "application",
    executableNames,
    pathFragments,
  };
}

function website(
  id: string,
  categoryId: string,
  name: string,
  description: string,
  websiteTarget: string,
  tags: string[],
  privacyNotice?: string,
): CatalogApplication {
  return {
    id,
    categoryId,
    name,
    description,
    officialUrl: websiteTarget,
    websiteTarget,
    tags,
    resourceType: "website",
    privacyNotice,
  };
}
